### ISSUE TITLE
Wallet Connection state in chromium based browsers

### ISSUE THREAD

**Issue by nrhs05** [osiastedian/syscoin-bridge#20]
Having intermittent issues on the bridge with it not always prompting for signatures, and I seem to somewhat be able to replicate it:

1. Start the process, but reject the burn so you have to click retry to get it to prompt the signature again. 
2. when its sitting on "check Pali wallet for signing   retry" open a new tab, and go to google and search anything (test, for example)
3. go back to the bridge tab and hit retry and see if it works, it wont for me in chrome and brave as it no longer knows the wallet is connected until you click the Pali icon in the top right to bring it back to life, seems to prompt to re-connect the wallet on the old bridge though when i do this and gets around it by doing that. 

The error in the console that shows is:

contentScript.bundle.js:1 Uncaught (in promise) Error: Connect an account and try again.
    at p (contentScript.bundle.js:1:17546)
p @ contentScript.bundle.js:1

I found waiting some time will also make this happen, so maybe something other tabs do while you are idle? so something is triggering the site to forget that the wallet is connected, and its not able to re-establish knowing its connected.

Not sure if this is a bridge issue, or more of a Pali issue though.

I found that sometimes when starting the bridge it was already in this state so it would never prompt you for the TXs in the first for burning sys and sysx, i am assuming this is why.

Windows 10
Brave 105 and Chrome 105

edit:

after looking a bit more, it seems like the main difference between FF and Chrome (when working/not working) iswhen you issue the ConnectionsController.connectWallet() it doesnt actually register the connection in the console and throws a promise error for the site in chromium. i am no dev, so i am just trying random things in hope it helps.

**Comment by function0xMarki** [comment]
It happens similar in Firefox, but I ruled out that it was a failure of the Bridge.

When you are on the main page, Pali Wallet takes a little longer to connect, meanwhile the "CONNECT" button appears.
When we click on that button, it connects immediately but before that the wallet is opened unnecessarily. However, if we wait a few seconds, it finally connects successfully.

https://user-images.githubusercontent.com/112655312/189204017-e3f4c0b7-7f0c-4fbc-bec5-fee058e8aa63.mov

The same thing happens during a bridge in progress, mainly caused by the fact that the wallet is blocked for security, and when entering the password it takes a few seconds to connect.

The same thing happens during a bridge in progress, when the wallet is locked for security, and entering the password takes a few seconds to connect.

Also when you click on the Pali Wallet add-on, it opens and connects immediately.

So it seems that Pali Wallet is slow to inform the Bridge of its presence.

https://user-images.githubusercontent.com/112655312/189205255-ef2e1d8c-269d-4f73-aa9c-ed00cf824d76.mov

When this happens, temporarily until it connects, the following error appears on the console:

- When this happens, temporarily until it connects, the following error appears on the console:

![Console_1.png](https://user-images.githubusercontent.com/112655312/189207683-243f279d-80f0-47c0-b099-4bbe975b52da.png)

![console_2](https://user-images.githubusercontent.com/112655312/189208798-801cd02e-8578-4772-b383-73c5a81c80f0.jpg)
