### ISSUE TITLE
Interface Modifications

### ISSUE THREAD

**Issue by function0xMarki** [osiastedian/syscoin-bridge#22]
Possible visual modifications to facilitate use for inexperienced users.

1. In the Bridge address exchange action button, increase the size of the icon and add a CSS animated "flash motion effect" to draw the user's attention.

https://user-images.githubusercontent.com/112655312/189551954-e35eaf36-db53-4bc3-8d59-2f1fe5a14c38.mov

2. Increase the Syscoin icon and add more separation between the logo and the text, leaving more cleanliness and separation between the logo and the text for better reading.

3. The texts, both Syscoin Network and Syscoin NEVM, through css with "letter-spacing: 0.15em", generate more space between letters and facilitate reading to better differentiate each one of them.

4. Delete "To" and "From" above the boxes, embedding them inside the boxes as "From Balance" and "To Balance".

5. Also, inside the box, add the balances that each wallet in each chain contains directly as "From Balance: X and To Balance: Y". The user may not be sure about the networks, but he knows perfectly well the balances he has in each of them, and therefore, it makes it easier for him to know where he is sending the SYS from.

![view_](https://user-images.githubusercontent.com/112655312/189552250-f1d3faac-ac62-4f7b-bde5-0d29c8cb74fa.jpg)

![view](https://user-images.githubusercontent.com/112655312/189552366-a35792d6-ad48-41aa-b1aa-dbf1b915ae92.jpg)

**Comment by osiastedian** [comment]
Hi @function0xMarki ,

For 1, I was thinking of using contained buttons instead of doing flashy animations.
For 2, Could you specify the size of the logo currently its `32x32` and how much space between the text is there. Currently using 48x48 with no additional margins
For 3, let's stick with [Material Design Typography](https://mui.com/material-ui/react-typography/#main-content). Using h6 instead
For 4, Ok updated.
For 5, Ok update. 
![Screen Shot 2022-09-14 at 9 55 03 PM](https://user-images.githubusercontent.com/11253903/190173718-7f0e4b27-8cc0-4141-97ec-05788c1e56d0.png)

**Comment by osiastedian** [comment]
You can view suggested changes here:

https://syscoin-bridge-git-22-interface-modifications-osiastedian.vercel.app/

**Comment by function0xMarki** [comment]
HI !

It's perfect !

**Comment by function0xMarki** [comment]
HI !

It's perfect !

**Comment by function0xMarki** [comment]
HI !

It's perfect !
