### ISSUE TITLE
TransferId in URL is an attack vector.   Numeric TransferId is also problematic

### ISSUE THREAD

**Issue by bstr156** [osiastedian/syscoin-bridge#7]
![image](https://user-images.githubusercontent.com/6069215/186533061-bfd04a64-b2dc-4b52-8dfa-70675dd8ccdd.png)

Best-practice is to avoid referencing session-related Ids through URL.  While there is some minor degree of randomization in TransferId, users can access other people's sessions by simply plugging-in the right number.

One might argue that the session is wallet-specific and thus in theory cannot be meaningfully hijacked at the asset level, but nevertheless this is an unnecessary vector to introduce into a UI dealing with digital assets, and as I said, is best-practice to not do this.

Demonstration 1:
1. Copy the URL from the browser A
2. Paste the URL into browser B

Demonstration 2:
Use a loop construct to iterate through the numeric Ids with a web client. I observe this would be easy to do because all the recent sessions I've done have had Id 1661374XXXXXX.

My suggestion is to exclusively read from the users wallet(s) to derive what is needed to identify their sessions (transfers), and not include the TransferId in the URL at all (not as a path nor as a parameter)

As an extra measure, I also suggest using a GUID for TransferId on the backend instead of a number.  Something that cannot be numerically iterated through.

**Comment by osiastedian** [comment]
@bstr156 

> users can access other people's sessions by simply plugging-in the right number.

> My suggestion is to exclusively read from the users wallet(s) to derive what is needed to identify their sessions (transfers)

People can still query the sessions of user based on their wallets on the API and get the transfer sessions.
```js
const sessions = await fetch('https://syscoin-bridge.vercel.app/api/transfer?utxo=<utxoAddress>&nevm=<nevmAddress>');
```

Not unless we always ask them to sign a message and on the backend we recover the addresses from the signed message.

But still, I don't think it really matter though because if some people really what to "KNOW" someone else's transfer session (and they are tech-savvy enough) they can easily go the blockchain explorer and scan the bridge contract transactions.

As long as these people can't alter the session itself I think is fine.

The main purpose of having the transfer id on the URL is that they can easily copy and paste it on another browser and continue their transfer rather than opening the app and do more clicks just to continue.

**Comment by bstr156** [comment]
My concern isn't about people seeing the transfers.  That's all public on the blockchain anyway. It's more about giving people an easy UI in which they can jump into other people's sessions. *If* there is some app level vulnerability we don't know about yet, that is the vector through which it is most likely to be exploited.

Just raising a concern.  You can close the ticket if you want.
